// GENERATED by tools/bake-content.mjs — do not edit by hand.
// Concrete, validated layouts for every generated stage. Regenerate after
// changing journey.js or challenges.js, and keep the content tests green.
export const BAKED = {
 "version": 1,
 "journey": {
  "ch1-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch1-s3": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch1-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch1-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch1-s6": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s1": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s3": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s6": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch2-s7": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s1": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s3": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 4,
     "c": 1,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 6,
     "c": 7,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s6": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch3-s7": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 6,
     "c": 1,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s1": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 7,
     "c": 2,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s3": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 5,
     "c": 2,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 5,
     "c": 2,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s6": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch4-s7": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch5-s1": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 7,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 2,
     "c": 5,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s3": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 5,
     "c": 4,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 5,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s6": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 3,
     "c": 6,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch5-s7": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 5,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 7,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 3,
     "c": 4,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch6-s2": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 4,
     "c": 9,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 8,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 8,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 9,
     "c": 2,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "ch6-s4": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 2,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 7,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 6,
     "c": 9,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 9,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 3,
     "c": 2,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch6-s5": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 1,
     "c": 0,
     "crowned": true
    }
   ],
   "turn": 0
  },
  "ch6-s7": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 7,
     "c": 4,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    }
   ],
   "turn": 0
  }
 },
 "challenges": {
  "surgical-strike": {
   "pieces": [
    {
     "owner": 0,
     "r": 2,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 1,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "cornered": {
   "pieces": [
    {
     "owner": 0,
     "r": 3,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 0,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 3,
     "c": 4,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 3,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 7,
     "c": 2,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 4,
     "c": 1,
     "crowned": false
    }
   ],
   "turn": 0
  },
  "kings-trial": {
   "pieces": [
    {
     "owner": 0,
     "r": 1,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 0,
     "c": 5,
     "crowned": false
    },
    {
     "owner": 0,
     "r": 7,
     "c": 0,
     "crowned": true
    },
    {
     "owner": 0,
     "r": 3,
     "c": 2,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 7,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 5,
     "c": 6,
     "crowned": false
    },
    {
     "owner": 1,
     "r": 6,
     "c": 5,
     "crowned": true
    },
    {
     "owner": 1,
     "r": 4,
     "c": 5,
     "crowned": true
    }
   ],
   "turn": 0
  }
 }
};
