// Bake content: resolve every generated journey/challenge layout into a
// concrete, validated position and write js/content/baked.js.
// Run: node tools/bake-content.mjs
import { writeFileSync } from 'node:fs';
import { JOURNEY_STAGES, resolveStage } from '../js/content/journey.js';
import { CHALLENGES } from '../js/content/challenges.js';
import { validateResolved } from '../js/content/validate.js';

const baked = { version: 1, journey: {}, challenges: {} };
let failures = 0;

for (const def of JOURNEY_STAGES) {
  const resolved = resolveStage(def);
  const res = validateResolved(resolved);
  const status = res.ok ? 'ok  ' : 'FAIL';
  console.log(`${status} ${def.id} ${def.name}${res.issues.length ? ' — ' + res.issues.join('; ') : ''}${resolved.proof?.plies ? ` (forced in ${resolved.proof.plies})` : ''} [${res.playout.plies} plies]`);
  if (!res.ok) failures += 1;
  if (resolved.setup) baked.journey[def.id] = resolved.setup;
}

for (const def of CHALLENGES) {
  if (!def.setup || def.setup === 'standard') continue;
  const resolved = resolveStage(def);
  const res = validateResolved(resolved);
  const status = res.ok ? 'ok  ' : 'FAIL';
  console.log(`${status} challenge/${def.id} ${def.name}${res.issues.length ? ' — ' + res.issues.join('; ') : ''}`);
  if (!res.ok) failures += 1;
  if (resolved.setup) baked.challenges[def.id] = resolved.setup;
}

const banner = `// GENERATED by tools/bake-content.mjs — do not edit by hand.\n// Concrete, validated layouts for every generated stage. Regenerate after\n// changing journey.js or challenges.js, and keep the content tests green.\n`;
writeFileSync(
  new URL('../js/content/baked.js', import.meta.url),
  `${banner}export const BAKED = ${JSON.stringify(baked, null, 1)};\n`,
);
console.log(failures ? `\n${failures} validation failure(s)` : '\nall content valid');
process.exit(failures ? 1 : 0);
